# Use an official Node.js runtime as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

RUN npm install recharts

# Copy the remaining application code to the working directory
COPY . .

# Build the application
RUN npm run build

# Expose the port that the application runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]
